export enum ActionTypes {
    QUESTION_ASK = 'QUESTION_ASK',
    QUESTION_ASK_REGISTERED = 'QUESTION_ASK_REGISTERED',
    QUESTION_LIST_REQUEST = 'QUESTION_LIST_REQUEST',
    QUESTION_LIST_REQUEST_SUCCESS = 'QUESTION_LIST_REQUEST_SUCCESS',
    QUESTION_LIST_REQUEST_FAILURE = 'QUESTION_LIST_REQUEST_FAILURE'
}

export interface Action{
    type:ActionTypes,
    data:any;
}
